ci: fix yaml syntax error in babel_job and audit_job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -34,7 +34,12 @@ lint_job:
 babel_job:
   stage: lint
   script:
-    - bash -c 'uv run pybabel extract . -o messages.pot --no-creation-date && if [ -n "$(git status --porcelain messages.pot)" ]; then echo "ERROR: message.pot has changed. Please run `git add messages.pot` and commit again."; exit 1; fi'
+    - |
+      uv run pybabel extract . -o messages.pot --no-creation-date
+      if [ -n "$(git status --porcelain messages.pot)" ]; then
+        echo "ERROR: messages.pot has changed. Please run 'git add messages.pot' and commit again."
+        exit 1
+      fi
   rules:
     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
@@ -70,7 +75,13 @@ vulture_job:
 audit_job:
   stage: test
   script:
-    - 'req="0.11.2"; cur=$(uv --version | cut -d" " -f2); if [ "$(printf "%s\n%s" "$req" "$cur" | sort -V | head -n1)" != "$req" ]; then echo "ERROR: uv v$cur is installed, but v$req or higher is required."; exit 1; fi'
+    - |
+      req="0.11.2"
+      cur=$(uv --version | cut -d" " -f2)
+      if [ "$(printf "%s\n%s" "$req" "$cur" | sort -V | head -n1)" != "$req" ]; then
+        echo "ERROR: uv v$cur is installed, but v$req or higher is required."
+        exit 1
+      fi
     - uv audit
   rules:
     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
